Implement user profile page: Update the profile picture
openkfw/innoverse pull request #137
Opened 2024-12-02 07:59 UTC by andrea-smiesna

Closes #54 

- [x] create a new page
- [x] add a new form with input fields (name, email, avatar, role, department)
- [x] add a new dropzone field for the images
- [x] change the session storage on the profile update
- [ ] save image and show the avatar in the form

2025-01-28 14:34 UTC, georgimld commented on app/components/common/form/ImagePreview.tsx
> +      <Image src={file} alt="preview" style={img} layout="fill" />
getting a warning here because of layout="fill" -> try this https://stackoverflow.com/questions/76652423/image-with-src-next-static-media-has-legacy-prop-layout-did-you-forge

2025-01-28 14:44 UTC, georgimld commented on app/utils/requests/innoUsers/requests.ts
> +      if (image !== 'null') {
i think this check is not ok, because sometimes the image is not null, but it is a string (url to the image) -> which leads to an error in the `uploadFileImage()` function: `Failed to execute 'append' on 'FormData': parameter 2 is not of type 'Blob'`

2025-01-28 14:54 UTC, georgimld commented on app/components/common/form/SaveButton.tsx
> +        Speichern
add translation entries for this please:

- [ ] en: "components_profilePage_form_updateUserForm_save": "Save"
- [ ] de: "components_profilePage_form_updateUserForm_save": "Speichern"

2025-01-28 15:32 UTC, georgimld requested changes
- [x] changing and deleting the user avatar works fine
- [x] when i update the department and/or the role, and also the avatar at the same time it works
- [x] when I update the department and/or the role (without updating the avatar) -> i get an error (the one [mentioned here](https://github.com/openkfw/innoverse/pull/137#discussion_r1932299843))
- [ ] if I add an avatar that's bigger than 1MB, i can click on "Save" but it doesn't work -> i get the following error in the backend: 
`uncaughtException:  [Error: Body exceeded 1 MB limit. To configure the body size limit for Server Actions, see: https://nextjs.org/docs/app/api-reference/next-config-js/serverActions#bodysizelimit] statusCode: 413}`
  -> the user should get a warning in the UI if the image is too large

2025-01-31 15:58 UTC, andrea-smiesna commented on app/utils/requests/innoUsers/requests.ts
> +      if (image !== 'null') {
Fixed

2025-01-31 15:58 UTC, andrea-smiesna commented on app/components/common/form/ImagePreview.tsx
> +      <Image src={file} alt="preview" style={img} layout="fill" />
Thanks for noticing. Added `layout="fill" sizes=""`

2025-02-04 15:15 UTC, pecirep requested changes

2025-02-04 15:15 UTC, pecirep commented on app/components/common/form/ImageDropzoneField.tsx
> +                ));
```suggestion
              const fileRejectionItems = fileRejections?.[0]?.errors.map((e) => (
                <FormHelperText key={e.code} sx={{ color: 'formText.main' }}>
                  {e.message}
                </FormHelperText>
              ));
```
I get an error when I access the user page because fileRejections is an empty list so the entry [0] is undefined

2025-02-04 15:15 UTC, pecirep commented on app/app/profile/page.tsx
The profile settings box has some negative space between the save button and and the bottom border and the copyright notice should be aligned with the bottom of the page but I'm not sure if the latter is related to this PR

<img width="1731" alt="image" src="https://github.com/user-attachments/assets/16207a59-c3eb-4c93-b22d-4289c76ca5e2" />

2025-02-10 10:49 UTC, andrea-smiesna commented on app/components/common/form/ImageDropzoneField.tsx
> +                ));
Thanks for noticing. Fixed.

2025-02-10 10:50 UTC, andrea-smiesna commented on app/app/profile/page.tsx
Done

2025-02-14 12:44 UTC, pecirep requested changes

2025-02-14 12:44 UTC, pecirep commented on app/components/userProfile/actions.ts
> +        ...body,
Passing in the entire body could allow someone to forge a request that could change more attributes than we might want them to. We already validate the params using zod so we should use that parsed output instead.

2025-02-14 12:44 UTC, pecirep commented on app/components/userProfile/validationSchema.ts
> +  email: z.string().email(),
since this is used as the input for the form submission, wouldn't it allow users to change their email, username, provider etc even if the form doesn't provide the inputs?

2025-02-14 13:03 UTC, pecirep commented on app/components/userProfile/validationSchema.ts
> +    .optional(),
since we only allow formData as the input for the image anyway, we can omit the union and use just `File`
```suggestion
  image: z.instanceof(File).refine((file) => file.size < MAX_FILE_SIZE, invalid_file_size).optional(),
```

2025-02-18 08:41 UTC, andrea-smiesna commented on app/components/userProfile/validationSchema.ts
> +  email: z.string().email(),
Fixed, thanks for noticing

2025-02-18 08:45 UTC, andrea-smiesna commented on app/components/userProfile/validationSchema.ts
> +    .optional(),
Since the validation schema is used also for the frontend, the "Speichern" button will be disabled if the image is string (not changed)/null (removed).
2 solutions: 
1. `z.union([z.any(), z.instanceof(File)....])`
2. create a separate zod schema which will be used for the fe and separate for the be

2025-02-24 08:35 UTC, pecirep commented on app/components/userProfile/validationSchema.ts
> +    .optional(),
I think whenever frontend and backend require different types for validation we should separate them so my vote goes to the second option

2025-02-27 13:01 UTC, pecirep requested changes
When no file size limit is set in the environment, the upload doesn't work but there is not error message, it just fails silently and there's an unhandled exception in the backend.

With the upload limit set, the form validation works but the error message doesn't say what the limit is.
![image](https://github.com/user-attachments/assets/df1ddb25-a58c-4ed9-a812-0f45e309ca04)

2025-03-27 16:27 UTC, georgimld approved these changes

2025-03-28 10:31 UTC, merged